apiVersion: extensions/v1beta1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  selector:
        app: web-svc
port:
        nodePort: 33001
        protocol: TCP
        port: 80
        targetPort: 80 
